Dev
dariavv/react-nav-blog pull request #1
Opened 2020-08-24 17:05 UTC by dariavv

![Снимок экрана 2020-08-24 в 20 04 09](https://user-images.githubusercontent.com/36665499/91074378-2076a600-e645-11ea-8925-4422f5994d27.png)

2020-08-26 08:05 UTC, K-AA requested changes
Awesome!

2020-08-26 08:05 UTC, K-AA commented on src/screens/MainScreen/index.tsx
> +        keyExtractor={(post: any) => post.id.toString()}
Please, try not to use callback functions like here. We have the ability to cache such a function

How can we cache a callback function? For such tasks, React has a set of caching and memoizing hooks, of which useCallback is the most suitable for us =>

Please, try not to use callback functions like here. We have the ability to cache such a function

How can we cache a callback function? For such tasks, React has a set of caching and memoizing hooks, of which useCallback is the most suitable for us =>

Please, try not to use callback functions like here. We have the ability to cache such a function

How can we cache a callback function? For such tasks, React has a set of caching and memoizing hooks, of which useCallback is the most suitable for us =>

`const keyExtractor = useCallback((post: any) => post.id.toString(), []);`

```
<View style={styles.container}>
      <FlatList
        data={DATA}
        keyExtractor={keyExtractor}
```

2020-08-26 08:18 UTC, MadaShindeInai requested changes

2020-08-26 08:18 UTC, MadaShindeInai commented on babel.config.js
>            screens: './src/screens',
cool!

2020-08-26 08:18 UTC, MadaShindeInai commented on src/components/Post/index.tsx
> +              {new Date(post.date).toLocaleDateString('en-GB')}
you can encode data for more interesting format.

2020-08-26 08:18 UTC, MadaShindeInai commented on src/components/Post/index.tsx
> +        <ImageBackground style={styles.image} source={{ uri: post.img }}>
you need to connect images locally. Try it

2020-08-26 08:18 UTC, MadaShindeInai commented on src/data.ts
> +    img:
use local images

2020-08-26 08:18 UTC, MadaShindeInai commented on src/navigation/AppNavigation/index.tsx
> +            title: `Post ${new Date(route.params.postDate).toLocaleDateString(
you can encode data to another format. it`s a good opportunity to try it!

2020-08-26 08:18 UTC, MadaShindeInai commented on src/screens/MainScreen/index.tsx
> +import DATA from 'data';
it`s just an opinion, but named exports are more safe then default

2020-08-26 08:18 UTC, MadaShindeInai commented on src/screens/PostScreen/index.tsx
> +  const post: PostType | undefined = DATA.find(
you solve error but do not solve problem!

2020-08-26 08:20 UTC, K-AA commented on src/screens/MainScreen/index.tsx
> +import DATA from 'data';
yep

2020-08-26 08:22 UTC, K-AA commented on src/components/Post/index.tsx
> +        <ImageBackground style={styles.image} source={{ uri: post.img }}>
awesome! I didn't see it

2020-08-26 08:24 UTC, K-AA commented on src/components/Post/index.tsx
> +              {new Date(post.date).toLocaleDateString('en-GB')}
and if you intend to work with Dates often, it is completely legal to instal 'date-fns'

2020-08-26 15:40 UTC, K-AA requested changes

2020-08-26 16:12 UTC, dariavv commented on src/screens/MainScreen/index.tsx
> +import DATA from 'data';
Thanks! Eslint swears at named exports. But I'll definitely try them in the next project.

2020-08-28 11:25 UTC, MadaShindeInai approved these changes

2020-08-28 11:25 UTC, MadaShindeInai commented on src/components/Post/index.tsx
> +const Post: React.FC<IPostProps> = ({ post, openItem }) => {
you also can wright FC without React if you import
import React, {FC} from 'react';

2020-08-28 11:25 UTC, MadaShindeInai commented on src/components/Post/index.tsx
> +              {format(new Date(post.date), 'dd-MM-yyyy HH:mm')}
date looks cool

2020-08-28 11:25 UTC, MadaShindeInai commented on src/data.ts
> +    img: require('../assets/images/5.jpeg'),
to unificate path you can write it from src/....

2020-08-28 11:25 UTC, MadaShindeInai commented on src/screens/MainScreen/index.tsx
> +
type MainScreenProps = {
  navigation: StackNavigationProp<
  AppNavigationParamList,
  'MainScreen'>
};
Is not working?

2020-08-28 11:25 UTC, MadaShindeInai commented on src/screens/MainScreen/index.tsx
> +  CreateScreen: undefined;
@K-AA do we need to describe this? Or we can skip it?

2020-08-28 11:25 UTC, MadaShindeInai commented on src/screens/PostScreen/index.tsx
> +  AboutScreen: undefined;
@K-AA do we need to describe this? Or we can skip this?

2020-08-28 11:31 UTC, dariavv commented on src/components/Post/index.tsx
> +const Post: React.FC<IPostProps> = ({ post, openItem }) => {
Yeah, I know. I like this way more. 
Is there any difference between them in terms of optimization?

2020-08-28 11:41 UTC, dariavv commented on src/screens/MainScreen/index.tsx
> +
I think if it was necessary to add a description of the route in this way, it would become unreadable. And I've already done the refactoring in the next commit :)

2020-08-28 11:46 UTC, dariavv commented on src/screens/MainScreen/index.tsx
> +  CreateScreen: undefined;
I made the description like this, but I'm not sure about the correctness.
I haven't implemented AboutScreen and CreateScreen yet.

export type AppNavigationParamList = {
  MainScreen: undefined;
  PostScreen: {
    postId: string;
    postDescription: string;
    postDate: string;
    isBooked: boolean;
  };
  BookedScreen: {
    openItem: (post: IPost) => void;
    keyExtractor: (post: IPost) => void;
    bookedData: any;
  };
  AboutScreen: undefined;
  CreateScreen: undefined;
};

2020-08-28 12:11 UTC, dariavv commented on src/screens/MainScreen/index.tsx
> +  CreateScreen: undefined;
But maybe you're right and I need to describe props for all the screens

2020-08-28 12:20 UTC, dariavv commented on src/screens/MainScreen/index.tsx
> +
And yes, it works :)

2020-09-02 11:14 UTC, merged