Navigation
dariavv/react-nav-blog pull request #2
Opened 2020-08-31 15:06 UTC by dariavv

![Снимок экрана 2020-08-31 в 18 04 34](https://user-images.githubusercontent.com/36665499/91735148-89fe3380-ebb4-11ea-829e-e9e4ca5eaf7e.png)

2020-09-01 07:31 UTC, MadaShindeInai requested changes

2020-09-01 07:31 UTC, MadaShindeInai commented on src/navigation/AppNavigation/index.tsx
> +          name="About App"
name is a keyword to move to screen with navigator. So, maybe it have a sense to write in in camelCase or OneWord?

2020-09-01 07:31 UTC, MadaShindeInai commented on src/navigation/StackNavigators/index.tsx
> +const BookedStack = createStackNavigator();
you can separate stack navigators to different files

2020-09-01 07:31 UTC, MadaShindeInai commented on src/navigation/StackNavigators/index.tsx
> +export const CreateStackScreen: React.FC = ({ navigation }: any) => {
what`s the use of this stack?

2020-09-01 07:31 UTC, MadaShindeInai commented on src/screens/BookedScreen/index.tsx
> +  const openItem = (post: IPost) => {
you can move this func to common file because it`s duplicated

2020-09-01 07:31 UTC, MadaShindeInai commented on src/screens/MainScreen/index.tsx
>      });
this func duplicated. move it to common file or to the utils folder

2020-09-01 12:21 UTC, dariavv commented on src/navigation/StackNavigators/index.tsx
> +const BookedStack = createStackNavigator();
ok, no problem :)

2020-09-01 13:23 UTC, dariavv commented on src/navigation/AppNavigation/index.tsx
> +          name="About App"
Yes, you're right) I mixed up with title.

2020-09-01 13:23 UTC, dariavv commented on src/navigation/StackNavigators/index.tsx
> +export const CreateStackScreen: React.FC = ({ navigation }: any) => {
I followed the course, I think this is a template for implementing the CreateScreen functionality.

2020-09-02 09:13 UTC, K-AA approved these changes

2020-09-02 10:56 UTC, dariavv commented on src/screens/MainScreen/index.tsx
>      });
Done!

2020-09-02 11:06 UTC, MadaShindeInai commented on src/navigation/StackNavigators/BookedStackScreen/index.tsx
> +          title: `Post ${format(
date-fns?

2020-09-02 11:08 UTC, MadaShindeInai approved these changes

2020-09-02 11:14 UTC, dariavv commented on src/navigation/StackNavigators/BookedStackScreen/index.tsx
> +          title: `Post ${format(
yep)

2020-09-02 11:14 UTC, merged